name: busyatra-backend

services:
  postgres:
    container_name: busyatra-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: busyatra
    ports:
      - "5434:5432"
    volumes:
      - busyatra_postgres_data:/var/lib/postgresql/data

volumes:
  busyatra_postgres_data:
